project_id = "mpgmxemqlrhiftlpzatu"

[functions.generate-image]
verify_jwt = false

[functions.generate-text]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.generate-video]
verify_jwt = false